### ISSUE TITLE
Forced to use local installation of PhantomJS

### ISSUE THREAD

**Issue by jlowery457** [karma-runner/karma-phantomjs-launcher#23]
For reasons I don't want to go into here we are forced to check our node_modules directory into GIT.  I would like to have a global npm install of PhantomJS and have the karma-phantomjs-launcher invoke this version instead of the one that gets automatically installed at node_modules/karma-phantomjs-launcher/node_modules/...

I have tried setting the environment variable PHANTOMJS_BIN to the location of the global phantomjs I would like to use, but either this is ignored or there is some config I am missing.

Node version: 0.10.22
Karma version: 0.10.8
karma-phantomjs-launcher version: 0.1.1
phantomjs version: 1.9.2

**Comment by vbauer** [comment]
* global install via npm install -g
* installed manually and set in PHANTOMJS_BIN

It does not work for me (v0.1.4).

**Comment by Dignifiedquire** [comment]
Should be solved with #70 hopefully

**Comment by ajones-miovision** [comment]
I am on ubuntu 14.04.3, and have phantom 2.1.1 installed locally on my system (not via npm). The phantomjs binary is in my PATH and I have exported PHANTOMJS_BIN. I have also tried installing phantomjs via npm with -g (because I want it installed globally). In either case, karma-phantom-launcher says:
10 02 2016 16:55:24.991:WARN [plugin]: Error during loading "/home/ajones/LocalSource/hosted/spectrum/node_modules/karma-phantomjs-launcher" plugin:
  Cannot find module 'phantomjs-prebuilt'
10 02 2016 16:55:25.084:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
10 02 2016 16:55:25.085:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?

The only way I can seem to get my tests to run with karma is if I install phantomjs locally in my project (which I do not want to do). 
Is this launcher unable to work with an instance of phantom install outside of the local project node_modules?

**Comment by adambiggs** [comment]
+1

PhantomJS installed globally via `$ npm install -g phantomjs-prebuilt`, and `PHANTOMJS_BIN` env var exported. Still get the following error:

```
11 03 2016 09:06:38.193:WARN [launcher]: Can not load "PhantomJS", it is not registered!
  Perhaps you are missing some plugin?
```

**Comment by skyscribe** [comment]
I hit exactly the same issue on Ubuntu 16.04, with latest version of modules:

- karma: 0.13.22
- phantomjs: 2.1.7
- phantomjs-prebuilt: 2.1.7
- karma-phantomjs-launcher: 1.0.0

Even after exporting `PHANTOMJS_BIN` to globally installed one, I still get below error:
```bash
24 05 2016 17:37:53.985:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
24 05 2016 17:37:53.986:WARN [launcher]: Can not load "phantomjs", it is not registered!
  Perhaps you are missing some plugin?
```
